//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_comment()
        {
            this.tb_comment1 = new HashSet<tb_comment>();
        }
    
        public int id_comment { get; set; }
        public int id_account { get; set; }
        public int id_cauhoi { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public string noi_dung { get; set; }
        public Nullable<int> reply_for { get; set; }
    
        public virtual tb_account tb_account { get; set; }
        public virtual tb_cauhoi tb_cauhoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_comment> tb_comment1 { get; set; }
        public virtual tb_comment tb_comment2 { get; set; }
    }
}
