//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cauhoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cauhoi()
        {
            this.tb_comment = new HashSet<tb_comment>();
            this.tb_dapan = new HashSet<tb_dapan>();
            this.tb_templatenoidung = new HashSet<tb_templatenoidung>();
        }
    
        public int id_cauhoi { get; set; }
        public int id_bai { get; set; }
        public bool xuat_ban { get; set; }
        public string loai_cau_hoi { get; set; }
        public string phuong_thuc_check_dap_an { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public string gia_tri_dung { get; set; }
        public int thu_tu { get; set; }
    
        public virtual tb_bai tb_bai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_comment> tb_comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_dapan> tb_dapan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_templatenoidung> tb_templatenoidung { get; set; }
    }
}
