//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_dapan
    {
        public int id_dapan { get; set; }
        public int id_cauhoi { get; set; }
        public string loai_dap_an { get; set; }
    
        public virtual tb_cauhoi tb_cauhoi { get; set; }
        public virtual tb_dapan_danhdau tb_dapan_danhdau { get; set; }
        public virtual tb_dapan_dientext tb_dapan_dientext { get; set; }
        public virtual tb_dapan_singlechoice tb_dapan_singlechoice { get; set; }
    }
}
