//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_templatenoidung_bainghe
    {
        public int id_templatenoidung { get; set; }
        public string url { get; set; }
    
        public virtual tb_templatenoidung tb_templatenoidung { get; set; }
    }
}
