//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_templatenoidung_hinhanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_templatenoidung_hinhanh()
        {
            this.tb_templatenoidunghinhanh_format = new HashSet<tb_templatenoidunghinhanh_format>();
        }
    
        public int id_templatenoidung { get; set; }
        public string url { get; set; }
    
        public virtual tb_templatenoidung tb_templatenoidung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_templatenoidunghinhanh_format> tb_templatenoidunghinhanh_format { get; set; }
    }
}
