//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_templatenoidung_text
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_templatenoidung_text()
        {
            this.tb_templatenoidungtext_format = new HashSet<tb_templatenoidungtext_format>();
        }
    
        public int id_templatenoidung { get; set; }
        public string noidung { get; set; }
    
        public virtual tb_templatenoidung tb_templatenoidung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_templatenoidungtext_format> tb_templatenoidungtext_format { get; set; }
    }
}
