//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_templatenoidung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_templatenoidung()
        {
            this.tb_bai = new HashSet<tb_bai>();
            this.tb_cauhoi = new HashSet<tb_cauhoi>();
        }
    
        public int id_templatenoidung { get; set; }
        public string loai_template { get; set; }
    
        public virtual tb_templatenoidung_bainghe tb_templatenoidung_bainghe { get; set; }
        public virtual tb_templatenoidung_hinhanh tb_templatenoidung_hinhanh { get; set; }
        public virtual tb_templatenoidung_text tb_templatenoidung_text { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_bai> tb_bai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_cauhoi> tb_cauhoi { get; set; }
    }
}
