//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_templatenoidungtext_format
    {
        public int id_format { get; set; }
        public int id_templatenoidungtext { get; set; }
        public string ckeditor_text_format { get; set; }
        public string template_width { get; set; }
        public string template_heigth { get; set; }
        public string template_alignment { get; set; }
    
        public virtual tb_templatenoidung_text tb_templatenoidung_text { get; set; }
    }
}
