//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_templatenoidunghinhanh_format
    {
        public int id_format { get; set; }
        public int id_templatenoidunghinhanh { get; set; }
        public string width { get; set; }
        public string height { get; set; }
        public string alignment { get; set; }
    
        public virtual tb_templatenoidung_hinhanh tb_templatenoidung_hinhanh { get; set; }
    }
}
